# Generated by Django 3.0 on 2019-12-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20191214_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
